[phases.install]
cmds = [
  "npm install --prefix Backend1",
  "npm install --prefix client"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "mkdir -p Backend1/client-dist && cp -r client/dist/* Backend1/client-dist/"
]

[start]
cmd = "npm start --prefix Backend1"
